/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOTAZIONE_H_RPCGEN
#define _VOTAZIONE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define NUMGIUDICI 10

struct Input {
	char *nomeCandidato;
	char tipoOp;
};
typedef struct Input Input;

struct Giudice {
	char *nome;
	int punteggioTot;
};
typedef struct Giudice Giudice;

struct Output {
	Giudice giudici[NUMGIUDICI];
};
typedef struct Output Output;

#define VOTAZIONE 0x20000013
#define VOTAZIONEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CLASSIFICA_GIUDICI 1
extern  Output * classifica_giudici_1(void *, CLIENT *);
extern  Output * classifica_giudici_1_svc(void *, struct svc_req *);
#define ESPRIMI_VOTO 2
extern  int * esprimi_voto_1(Input *, CLIENT *);
extern  int * esprimi_voto_1_svc(Input *, struct svc_req *);
extern int votazione_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CLASSIFICA_GIUDICI 1
extern  Output * classifica_giudici_1();
extern  Output * classifica_giudici_1_svc();
#define ESPRIMI_VOTO 2
extern  int * esprimi_voto_1();
extern  int * esprimi_voto_1_svc();
extern int votazione_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_Giudice (XDR *, Giudice*);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_Input ();
extern bool_t xdr_Giudice ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VOTAZIONE_H_RPCGEN */
